project:
  type: website

execute:
  enabled: true

website:
  title: "Natalie Baclawski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About



