project:
  type: website

execute:
  enabled: true

website:
  title: "Natalie Baclawski"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: projects.qmd
        text: "Projects"
      - href: cv.qmd
        text: "CV"
      - href: contact.qmd
        text: "Contact"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

execute:
  echo: false